// export const domesticos=[
//     "Televisor",
// "Monitor",
// "Equipo de sonido",
// "Horno eléctrico",
// "Cocina eléctrica",
// "Refrigeradoras",
// "Campana extractora de aire",
// "Microondas",
// "Aire acondicionado",
// "Ventilador",
// "Lavadora",
// "Secadora",
// "Ordenador de mesa",
// "Impresora",
// "Cafetera",
// "Tostadora",
// "Plancha",
// "Secadora de pelo",
// "Aspiradora",
// ]

export const domesticos:Domestico[]=[
    {nombre:"Televisor", consumo_nominal:15, horas_uso:0},
{nombre:"Monitor", consumo_nominal:2, horas_uso:0},
{nombre:"Equipo de sonido", consumo_nominal:0, horas_uso:0},
{nombre:"Horno eléctrico", consumo_nominal:0, horas_uso:0},
{nombre:"Cocina eléctrica", consumo_nominal:0, horas_uso:0},
{nombre:"Refrigeradoras", consumo_nominal:500, horas_uso:0},
{nombre:"Campana extractora de aire", consumo_nominal:0, horas_uso:0},
{nombre:"Microondas", consumo_nominal:0, horas_uso:0},
{nombre:"Aire acondicionado", consumo_nominal:0, horas_uso:0},
{nombre:"Ventilador", consumo_nominal:0, horas_uso:0},
{nombre:"Lavadora", consumo_nominal:0, horas_uso:0},
{nombre:"Secadora", consumo_nominal:0, horas_uso:0},
{nombre:"Ordenador de mesa", consumo_nominal:0, horas_uso:0},
{nombre:"Impresora", consumo_nominal:0, horas_uso:0},
{nombre:"Cafetera", consumo_nominal:0, horas_uso:0},
{nombre:"Tostadora", consumo_nominal:0, horas_uso:0},
{nombre:"Plancha", consumo_nominal:0, horas_uso:0},
{nombre:"Secadora de pelo", consumo_nominal:0, horas_uso:0},
{nombre:"Aspiradora", consumo_nominal:0, horas_uso:0},
]